#!/usr/bin/env bun
import path from "path"; // Bun supports 'path' module from Node
import { existsSync, readFileSync, writeFileSync } from "fs"; // Bun supports 'fs' module from Node
import { $, env, write } from "bun";

const apiToken = env.API_TOKEN;
const args = process.argv.slice(2);
const filename = args[0];
const dataFilename = args[1] ?? "data.txt";

if (!filename) throw new Error("You need to pass in a filename to run!");
if (!apiToken) throw new Error("API_TOKEN not set");

const absolutePath = path.resolve(filename);
const folder = path.basename(path.dirname(absolutePath));
const dataFile = path.join(folder, dataFilename);

const match = folder.match(/day(\d*)/i);
const day = match ? parseInt(match[1], 10) : null;
if (!day) throw new Error("Folder does not match day.*");

if (dataFilename === "data.txt" && !existsSync(dataFile)) {
  console.log(`Fetching input for Day ${day} from Advent of Code...`);
  const response = await fetch(
    `https://adventofcode.com/2025/day/${day}/input`,
    { headers: { Cookie: `session=${apiToken}` } }
  );
  if (!response.ok) throw new Error(`HTTP Error: ${response.statusText}`);
  await write(dataFile, await response.text());
}

if (!existsSync(dataFile)) throw new Error("Data does not exist");

// console.log(`cat ${dataFile} | bun run ${absolutePath}`);
await $`cat ${dataFile} | bun run ${absolutePath}`.nothrow();
